apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
  name: first-app
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      recurse: true
    path: manifests/set0
    repoURL: http://git.tnc.bootcamp.lab:3000/student/ocp-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
