apiVersion: v1:
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  creationTimestamp: null
  name: argotest2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "301"
  name: cli-job-sa
  namespace: argotest2
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "302"
  name: cli-job-sa-argotest2-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cli-job-sa
    namespace: argotest2
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "303"
  name: testjob2-2
  namespace: argotest2
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
      containers:
        - image: registry.redhat.io/openshift4/ose-tools-rhel8:latest 
          name: testjob2-2
          command:
            - /bin/bash
            - -c
            - |
              for count in {1..10}; do echo "job2: " $count; sleep 10; done
