---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "103"
  name: presync1
  namespace: argotest2
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      # serviceAccount: cli-job-sa
      # serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
      containers:
        - image: quay.tnc.bootcamp.lab:8443/sfhassan/oc_net_tools
          name: presync1
          command:
            - /bin/bash
            - -c
            - |
              for count in {1..10}; do echo -n ".....presync1...."; echo  $count; sleep 10; done
